### ISSUE TITLE
Versionierung der Webanwendungen automatisieren

### ISSUE THREAD

**Issue by DominikDeisner** [minova-afis/aero.minova.os.github.workflows#23]
# Automatisierte Versionierung der Webanwendungen

## Beschreibung:

Um die Versionierung deiner Anwendung in der package.json automatisiert mit GitHub zu verwalten, kannst du verschiedene Tools und Ansätze verwenden. Ein häufig verwendetes Tool ist semantic-release, das den Versionsnummerierungsprozess und das Veröffentlichen neuer Versionen basierend auf Git-Kommentaren automatisiert.

# Schritte zur Automatisierung der Versionierung mit semantic-release
Installiere semantic-release und benötigte Plugins:

```bash
npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
```
## Konfiguriere semantic-release:
Erstelle eine Datei namens .releaserc im Stammverzeichnis deines Projekts mit folgendem Inhalt:

```json
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", {
      "npmPublish": false
    }],
    ["@semantic-release/git", {
      "assets": ["package.json", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
}
```

## Konfiguriere GitHub Actions:
Erstelle eine Datei **`.github/workflows/release.yml`** mit folgendem Inhalt:

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
```
Stelle sicher, dass du ein GitHub-Personal-Access-Token (GITHUB_TOKEN) konfiguriert hast, falls erforderlich.

## Schreibe konventionelle Commits:
Verwende konventionelle Commit-Nachrichten, damit semantic-release die Änderungen korrekt analysieren kann. Beispiele für konventionelle Commit-Nachrichten sind:

```
feat: Neues Feature
fix: Bugfix
chore: Dependencies Update
```

## Erstellen und Veröffentlichen:

Jedes Mal, wenn du in den main Branch pushst, wird GitHub Actions die semantic-release Pipeline ausführen, die Version in der `package.json` aktualisieren, eine neue Release auf GitHub erstellen und die Änderungen zurück in den main Branch pushen.

### Vorteile dieser Methode
**Automatische Versionierung:** Basierend auf Commit-Nachrichten werden Versionen automatisch erstellt.

**Changelog-Generierung:** Automatisch generierte Changelogs basierend auf Commit-Nachrichten.

**Nahtlose Integration:** Gut integriert mit CI/CD-Pipelines wie GitHub Actions.

Indem du diese Schritte befolgst, kannst du die Versionierung deiner Anwendung in der package.json automatisieren und sicherstellen, dass immer die korrekte Versionierung und Dokumentation deiner Releases vorhanden ist.

Abrechnung={XXX/XXX/XXX/ZPROGRAM}
